INSERT INTO `estados` (`id`, `sigla`, `nome`) VALUES (1, 'AC', 'Acre');
INSERT INTO `estados` (`id`, `sigla`, `nome`) VALUES (2, 'AL', 'Alagoas');
INSERT INTO `estados` (`id`, `sigla`, `nome`) VALUES (3, 'AP', 'Amapa');
INSERT INTO `estados` (`id`, `sigla`, `nome`) VALUES (4, 'AM', 'Amazonas');
INSERT INTO `estados` (`id`, `sigla`, `nome`) VALUES (5, 'BA', 'Bahia');
INSERT INTO `estados` (`id`, `sigla`, `nome`) VALUES (6, 'CE', 'Ceara');
INSERT INTO `estados` (`id`, `sigla`, `nome`) VALUES (7, 'DF', 'Distrito Federal');
INSERT INTO `estados` (`id`, `sigla`, `nome`) VALUES (8, 'ES', 'Espirito Santo');
INSERT INTO `estados` (`id`, `sigla`, `nome`) VALUES (9, 'GO', 'Goias');
INSERT INTO `estados` (`id`, `sigla`, `nome`) VALUES (10, 'MA', 'Maranhao');
INSERT INTO `estados` (`id`, `sigla`, `nome`) VALUES (11, 'MT', 'Mato Grosso');
INSERT INTO `estados` (`id`, `sigla`, `nome`) VALUES (12, 'MS', 'Mato Grosso do Sul');
INSERT INTO `estados` (`id`, `sigla`, `nome`) VALUES (13, 'MG', 'Minas Gerais');
INSERT INTO `estados` (`id`, `sigla`, `nome`) VALUES (14, 'PA', 'Para');
INSERT INTO `estados` (`id`, `sigla`, `nome`) VALUES (15, 'PB', 'Paraiba');
INSERT INTO `estados` (`id`, `sigla`, `nome`) VALUES (16, 'PR', 'Parana');
INSERT INTO `estados` (`id`, `sigla`, `nome`) VALUES (17, 'PE', 'Pernambuco');
INSERT INTO `estados` (`id`, `sigla`, `nome`) VALUES (18, 'PI', 'Piaui');
INSERT INTO `estados` (`id`, `sigla`, `nome`) VALUES (19, 'RJ', 'Rio de Janeiro');
INSERT INTO `estados` (`id`, `sigla`, `nome`) VALUES (20, 'RN', 'Rio Grande do Norte');
INSERT INTO `estados` (`id`, `sigla`, `nome`) VALUES (21, 'RS', 'Rio Grande do Sul');
INSERT INTO `estados` (`id`, `sigla`, `nome`) VALUES (22, 'RO', 'Rondonia');
INSERT INTO `estados` (`id`, `sigla`, `nome`) VALUES (23, 'RR', 'Roraima');
INSERT INTO `estados` (`id`, `sigla`, `nome`) VALUES (24, 'SC', 'Santa Catarina');
INSERT INTO `estados` (`id`, `sigla`, `nome`) VALUES (25, 'SP', 'Sao Paulo');
INSERT INTO `estados` (`id`, `sigla`, `nome`) VALUES (26, 'SE', 'Sergipe');
INSERT INTO `estados` (`id`, `sigla`, `nome`) VALUES (27, 'TO', 'Tocantins');
