INSERT INTO `orgao` (`id`, `nome`) VALUES (1, 'Câmara Cível');
INSERT INTO `orgao` (`id`, `nome`) VALUES (2, 'Câmara Criminal');
INSERT INTO `orgao` (`id`, `nome`) VALUES (3, 'Juizado Especial Cível');
INSERT INTO `orgao` (`id`, `nome`) VALUES (4, 'Juizado Especial Criminal');
INSERT INTO `orgao` (`id`, `nome`) VALUES (5, 'Juizado Especial Federal');
INSERT INTO `orgao` (`id`, `nome`) VALUES (6, 'Órgão Especial');
INSERT INTO `orgao` (`id`, `nome`) VALUES (7, 'Pleno');
INSERT INTO `orgao` (`id`, `nome`) VALUES (8, 'Presidência');
INSERT INTO `orgao` (`id`, `nome`) VALUES (9, 'Tribunal Pleno');
INSERT INTO `orgao` (`id`, `nome`) VALUES (10, 'Turma do STF');
INSERT INTO `orgao` (`id`, `nome`) VALUES (11, 'Turma do STJ');
INSERT INTO `orgao` (`id`, `nome`) VALUES (12, 'Turma do TRF');
INSERT INTO `orgao` (`id`, `nome`) VALUES (13, 'Turma do TRT');
INSERT INTO `orgao` (`id`, `nome`) VALUES (14, 'Turma do TST');
INSERT INTO `orgao` (`id`, `nome`) VALUES (15, 'Turma Recursal do Juizado Especial Cível');
INSERT INTO `orgao` (`id`, `nome`) VALUES (16, 'Turma Recursal do Juizado Especial Criminal');
INSERT INTO `orgao` (`id`, `nome`) VALUES (17, 'Vara Cível');
INSERT INTO `orgao` (`id`, `nome`) VALUES (18, 'Vara Criminal');
INSERT INTO `orgao` (`id`, `nome`) VALUES (19, 'Vara da Infância e da Juventude');
INSERT INTO `orgao` (`id`, `nome`) VALUES (20, 'Vara de Fazenda Pública');
INSERT INTO `orgao` (`id`, `nome`) VALUES (21, 'Vara de Órfãos e Sucessões');
INSERT INTO `orgao` (`id`, `nome`) VALUES (22, 'Vara do Sistema dos Juizados Especiais');
INSERT INTO `orgao` (`id`, `nome`) VALUES (23, 'Vara do Trabalho');
INSERT INTO `orgao` (`id`, `nome`) VALUES (24, 'Vara Empresarial');
INSERT INTO `orgao` (`id`, `nome`) VALUES (25, 'Vara Execução Penal');
INSERT INTO `orgao` (`id`, `nome`) VALUES (26, 'Vara Federal');
INSERT INTO `orgao` (`id`, `nome`) VALUES (27, 'Vice-Presidência');
